// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "../Verifier.sol";

/**
 * @title KZGVerifierTest
 * @notice Foundry test suite for the KZGVerifier contract.
 *
 * Values generated by `node src/deploy_and_test.js`:
 *   Circuit: x*x = y,  x = 3,  y = 9
 *   Trusted setup: tau = 7  (DEMO ONLY — use a real ceremony in production)
 *   Polynomial: A(x) = QAP left polynomial (depends on witness w for x=3)
 *   Evaluation point: z = 42
 *   A(42) = 249
 *
 * G1 points lie on: y^2 = x^3 + 3  mod  q
 *   where q = 21888242871839275222246405745257275088696311157297823662689037894645226208583
 *   (EIP-196 coordinate field prime, = CURVE_ORDER in our old field.js naming)
 *
 * G2 encoding (EIP-197): [x_imaginary, x_real, y_imaginary, y_real]
 */
contract KZGVerifierTest is Test {
    KZGVerifier verifier;

    // tau*G2 from JS with tau = 7
    uint256 constant TAU_G2_X1 =
        18551411094430470096460536606940536822990217226529861227533666875800903099477;
    uint256 constant TAU_G2_X0 =
        15512671280233143720612069991584289591749188907863576513414377951116606878472;
    uint256 constant TAU_G2_Y1 =
        1711576522631428957817575436337311654689480489843856945284031697403898093784;
    uint256 constant TAU_G2_Y0 =
        13376798835316611669264291046140500151806347092962367781523498857425536295743;

    // Commitment C = A(tau)*G1  (x=3, tau=7)
    uint256 constant COMMITMENT_X =
        12231734685659393914320260566447712574192421431051443092223777906741357260966;
    uint256 constant COMMITMENT_Y =
        17727947864982905001040320444642043959882380122793290910937606141681385178793;
    uint256 constant EVAL_Z   = 42;
    uint256 constant EVAL_Y   = 249;
    // pi = q(tau)*G1  (quotient poly = 6, so pi = 6*G1)
    uint256 constant PI_X     =
        4503322228978077916651710446042370109107355802721800704639343137502100212473;
    uint256 constant PI_Y     =
        6132642251294427119375180147349983541569387941788025780665104001559216576968;

    function setUp() public {
        verifier = new KZGVerifier(TAU_G2_X1, TAU_G2_X0, TAU_G2_Y1, TAU_G2_Y0);
    }

    function validProof() internal pure returns (KZGVerifier.Proof memory) {
        return KZGVerifier.Proof({
            commitment: KZGVerifier.G1Point({ x: COMMITMENT_X, y: COMMITMENT_Y }),
            z:          EVAL_Z,
            y_eval:     EVAL_Y,
            pi:         KZGVerifier.G1Point({ x: PI_X, y: PI_Y })
        });
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Test 1: Valid proof passes
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * @notice The EVM ecPairing precompile (0x08) must accept the valid proof.
     *
     * Pairing equation checked:
     *   e(C - y*G1 + z*pi, G2) * e(-pi, tau*G2) == 1
     */
    function test_validProofVerifies() public {
        bool result = verifier.verifyKZG(validProof());
        assertTrue(result, "Valid KZG proof should verify");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Test 2: Whitelist is set after valid proof
    // ─────────────────────────────────────────────────────────────────────────

    function test_whitelistSetAfterValidProof() public {
        address prover = address(0xBEEF);
        vm.prank(prover);
        verifier.verifyKZG(validProof());
        assertTrue(verifier.whitelist(prover), "Prover should be whitelisted");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Test 3: WhitelistAdded event
    // ─────────────────────────────────────────────────────────────────────────

    function test_whitelistEventEmitted() public {
        address prover = address(0xCAFE);
        vm.expectEmit(true, false, false, false);
        emit KZGVerifier.WhitelistAdded(prover);
        vm.prank(prover);
        verifier.verifyKZG(validProof());
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Test 4: Wrong y_eval fails
    // ─────────────────────────────────────────────────────────────────────────

    function test_wrongYEvalFails() public {
        KZGVerifier.Proof memory proof = validProof();
        proof.y_eval = proof.y_eval + 1;
        assertFalse(verifier.verifyKZG(proof), "Wrong y_eval should fail");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Test 5: Wrong commitment fails
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * @notice 3*G1 is a valid EIP-196 alt_bn128 point but the wrong commitment.
     * 3*G1 = ecMul(G1, 3) on the standard curve.
     */
    function test_wrongCommitmentFails() public {
        KZGVerifier.Proof memory proof = validProof();
        // 3*G1 on alt_bn128 — valid EIP-196 curve point but wrong commitment.
        // (bn254.G1.ProjectivePoint.BASE.multiply(3n).toAffine())
        proof.commitment = KZGVerifier.G1Point({
            x: 3353031288059533942658390886683067124040920775575537747144343083137631628272,
            y: 19321533766552368860946552437480515441416830039777911637913418824951667761761
        });
        assertFalse(verifier.verifyKZG(proof), "Wrong commitment should fail");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Test 6: Wrong pi fails
    // ─────────────────────────────────────────────────────────────────────────

    function test_wrongPiFails() public {
        KZGVerifier.Proof memory proof = validProof();
        proof.pi = KZGVerifier.G1Point({ x: 1, y: 2 }); // G1 generator — wrong pi
        assertFalse(verifier.verifyKZG(proof), "Wrong pi should fail");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Test 7: verifyKZGView consistency
    // ─────────────────────────────────────────────────────────────────────────

    function test_viewFunctionConsistentValid() public view {
        assertTrue(verifier.verifyKZGView(validProof()), "View: valid proof");
    }

    function test_viewFunctionConsistentInvalid() public view {
        KZGVerifier.Proof memory proof = validProof();
        proof.y_eval = proof.y_eval + 1;
        assertFalse(verifier.verifyKZGView(proof), "View: tampered proof should fail");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Test 8: Whitelist NOT set on invalid proof
    // ─────────────────────────────────────────────────────────────────────────

    function test_whitelistNotSetOnInvalidProof() public {
        address prover = address(0xDEAD);
        KZGVerifier.Proof memory proof = validProof();
        proof.y_eval = proof.y_eval + 1;
        vm.prank(prover);
        assertFalse(verifier.verifyKZG(proof));
        assertFalse(verifier.whitelist(prover));
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Test 9: Multiple provers can be whitelisted
    // ─────────────────────────────────────────────────────────────────────────

    function test_multipleProversCanBeWhitelisted() public {
        address alice = address(0x1111);
        address bob   = address(0x2222);
        vm.prank(alice);
        verifier.verifyKZG(validProof());
        vm.prank(bob);
        verifier.verifyKZG(validProof());
        assertTrue(verifier.whitelist(alice), "Alice should be whitelisted");
        assertTrue(verifier.whitelist(bob),   "Bob should be whitelisted");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Test 10: tau*G2 stored correctly
    // ─────────────────────────────────────────────────────────────────────────

    function test_tauG2StoredCorrectly() public view {
        assertEq(verifier.TAU_G2_X1(), TAU_G2_X1);
        assertEq(verifier.TAU_G2_X0(), TAU_G2_X0);
        assertEq(verifier.TAU_G2_Y1(), TAU_G2_Y1);
        assertEq(verifier.TAU_G2_Y0(), TAU_G2_Y0);
    }
}
